// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as EditService from "./editservice.js";
export {
    EditService
};

export {
    SigilTrait,
    TraitInfo
} from "./models.js";
