// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EditService is the Wails-exposed backend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Install writes the ordered edit list plus the mod binary into the Reloaded-II
 * mods folder. The list order is the precedence order.
 * @param {$models.SkillEdit[] | null} edits
 * @returns {$CancellablePromise<string>}
 */
export function Install(edits) {
    return $Call.ByID(1551222132, edits);
}

/**
 * LoadEdits reads the current edit list from the installed mod's Config.json,
 * falling back to defaults when it is missing or unreadable.
 * @returns {$CancellablePromise<$models.SkillEdit[] | null>}
 */
export function LoadEdits() {
    return $Call.ByID(3740291038);
}

/**
 * ModsDir returns the Reloaded-II mods folder, or "" when it cannot be found.
 * @returns {$CancellablePromise<string>}
 */
export function ModsDir() {
    return $Call.ByID(2742366571);
}

/**
 * NameMap returns the whole key -> name table so the frontend can resolve
 * names locally instead of one call per row.
 * @returns {$CancellablePromise<{ [_ in string]?: string } | null>}
 */
export function NameMap() {
    return $Call.ByID(2661837316);
}

/**
 * NameOf returns the display name for a skill key, or "" when unknown.
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function NameOf(key) {
    return $Call.ByID(696980779, key);
}
