// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as EditService from "./editservice.js";
export {
    EditService
};

import * as $models from "./models.js";

/**
 * SkillEdit mirrors the mod's Config.cs SkillEdit: one skill_status row override.
 * @typedef {$models.SkillEdit} SkillEdit
 */
