// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillEdit mirrors the mod's Config.cs SkillEdit: one skill_status row override.
 * @typedef {Object} SkillEdit
 * @property {boolean} Enabled
 * @property {string} Key
 * @property {number} Level
 * @property {number} Value1
 * @property {number} Value2
 * @property {number} Value3
 */

// In interface mode, this file is likely to contain just comments.
// We add a dummy export statement to ensure it is recognised as an ES module.
export {};
