// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SkillEdit mirrors the mod's Config.cs SkillEdit: one skill_status row override.
 * Values maps positionally onto LevelValue1..10, which is what the skill's own
 * description uses as {0}, {1}, {2} ...
 */
export class SkillEdit {
    /**
     * Creates a new SkillEdit instance.
     * @param {Partial<SkillEdit>} [$$source = {}] - The source object to create the SkillEdit.
     */
    constructor($$source = {}) {
        if (!("Enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }
        if (!("Key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Key"] = "";
        }
        if (!("Level" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Level"] = 0;
        }
        if (!("Values" in $$source)) {
            /**
             * @member
             * @type {number[]}
             */
            this["Values"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillEdit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillEdit}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Values" in $$parsedSource) {
            $$parsedSource["Values"] = $$createField3_0($$parsedSource["Values"]);
        }
        return new SkillEdit(/** @type {Partial<SkillEdit>} */($$parsedSource));
    }
}

/**
 * SkillInfo is one row of the generated skillinfo.json: every level of a skill the
 * tool offers, so a newly added edit starts from the game's own numbers instead of
 * zeros, and so the value shown for a slot - and the one an emptied box writes back
 * - is the game's number for the level the edit names.
 * 
 * Levels is indexed by level - 1: Levels[3] is the row whose Level field is 4.
 * 
 * Default is the level a new edit should start on: the skill's own maximum when
 * that is a normal 20 or less, otherwise the usual 15, except for the few skills
 * whose values only exist higher up. Min and Max are what the level field is
 * clamped to - Min is the lowest level carrying numbers, so a skill whose numbers
 * exist on one level only cannot be moved off it.
 */
export class SkillInfo {
    /**
     * Creates a new SkillInfo instance.
     * @param {Partial<SkillInfo>} [$$source = {}] - The source object to create the SkillInfo.
     */
    constructor($$source = {}) {
        if (!("Levels" in $$source)) {
            /**
             * @member
             * @type {number[][]}
             */
            this["Levels"] = [];
        }
        if (!("Default" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Default"] = 0;
        }
        if (!("Max" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Max"] = 0;
        }
        if (!("Min" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["Min"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SkillInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SkillInfo}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Levels" in $$parsedSource) {
            $$parsedSource["Levels"] = $$createField0_0($$parsedSource["Levels"]);
        }
        return new SkillInfo(/** @type {Partial<SkillInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
